apiVersion: v1
kind: Service
metadata:
  labels:
    app: fluentd
    section.io/logstream-destination: "true"
  name: fluentd
  namespace: default
spec:
  ports:
  - name: fluentdudp
    port: 5160
    protocol: UDP
    targetPort: 5160
  selector:
    app: fluentd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd
  namespace: default
  labels:
    app: fluentd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
        section.io/logstream-collect: "false"
    spec:
      containers:
      - name: fluentd
        image: grafana/fluent-plugin-loki:master
        imagePullPolicy: Always
        resources:
          requests:
            memory: ".2Gi"
            cpu: "200m"
          limits:
            memory: ".2Gi"
            cpu: "200m"
        volumeMounts:
        - name: config
          mountPath: /fluentd/etc/fluent.conf
          readOnly: true
          subPath: fluent.conf
      volumes:
      - name: config
        configMap:
          name: fluent-conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-conf
  namespace: default
data:
  fluent.conf: |-
    <source>
      @type udp
      tag udpsource
      <parse>
        @type json
      </parse>
      port 5160
      message_length_limit 1MB
    </source>


    <match udpsource>
      @type loki
      url "FILL_THIS_IN"
      username "FILL_THIS_IN"
      password "FILL_THIS_IN"
      extra_labels {"env":"prod"}
    </match>